openapi: 3.0.0
info:
  title: Hello World API
  description: A simple API to return a Hello World message
  version: "1.0"
servers:
  - url: https://sharp-moria-avon18-b017b82a.koyeb.app/
paths:
  /:
    get:
      summary: Returns a Hello World message
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
        401:
          description: Unauthorized access