openapi: 3.1.0
info:
  title: Hello World API
  description: A simple API to return a Hello World message
  version: "1.0"
servers:
  - url: https://sharp-moria-avon18-b017b82a.koyeb.app/
components:
  securitySchemes:
    ApiKeyAuth:  # Arbitrary name for the security scheme
      type: apiKey
      in: header  # can be "header", "query" or "cookie"
      name: API-Key  # name of the header, query parameter, or cookie
security:
  - ApiKeyAuth: []
paths:
  /:
    get:
      summary: Returns a Hello World message
      operationId: helloWorld
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
        401:
          description: Unauthorized access